# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LinearTerm', [dirname(__file__)])
        except ImportError:
            import _LinearTerm
            return _LinearTerm
        if fp is not None:
            try:
                _mod = imp.load_module('_LinearTerm', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LinearTerm = swig_import_helper()
    del swig_import_helper
else:
    import _LinearTerm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LinearTerm.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _LinearTerm.SwigPyIterator_value(self)
    def incr(self, n=1): return _LinearTerm.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _LinearTerm.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _LinearTerm.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _LinearTerm.SwigPyIterator_equal(self, *args)
    def copy(self): return _LinearTerm.SwigPyIterator_copy(self)
    def next(self): return _LinearTerm.SwigPyIterator_next(self)
    def __next__(self): return _LinearTerm.SwigPyIterator___next__(self)
    def previous(self): return _LinearTerm.SwigPyIterator_previous(self)
    def advance(self, *args): return _LinearTerm.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _LinearTerm.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _LinearTerm.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _LinearTerm.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _LinearTerm.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _LinearTerm.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _LinearTerm.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _LinearTerm.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _LinearTerm.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _LinearTerm.DoubleVector___nonzero__(self)
    def __bool__(self): return _LinearTerm.DoubleVector___bool__(self)
    def __len__(self): return _LinearTerm.DoubleVector___len__(self)
    def pop(self): return _LinearTerm.DoubleVector_pop(self)
    def __getslice__(self, *args): return _LinearTerm.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _LinearTerm.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _LinearTerm.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _LinearTerm.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _LinearTerm.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _LinearTerm.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _LinearTerm.DoubleVector_append(self, *args)
    def empty(self): return _LinearTerm.DoubleVector_empty(self)
    def size(self): return _LinearTerm.DoubleVector_size(self)
    def clear(self): return _LinearTerm.DoubleVector_clear(self)
    def swap(self, *args): return _LinearTerm.DoubleVector_swap(self, *args)
    def get_allocator(self): return _LinearTerm.DoubleVector_get_allocator(self)
    def begin(self): return _LinearTerm.DoubleVector_begin(self)
    def end(self): return _LinearTerm.DoubleVector_end(self)
    def rbegin(self): return _LinearTerm.DoubleVector_rbegin(self)
    def rend(self): return _LinearTerm.DoubleVector_rend(self)
    def pop_back(self): return _LinearTerm.DoubleVector_pop_back(self)
    def erase(self, *args): return _LinearTerm.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _LinearTerm.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _LinearTerm.DoubleVector_push_back(self, *args)
    def front(self): return _LinearTerm.DoubleVector_front(self)
    def back(self): return _LinearTerm.DoubleVector_back(self)
    def assign(self, *args): return _LinearTerm.DoubleVector_assign(self, *args)
    def resize(self, *args): return _LinearTerm.DoubleVector_resize(self, *args)
    def insert(self, *args): return _LinearTerm.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _LinearTerm.DoubleVector_reserve(self, *args)
    def capacity(self): return _LinearTerm.DoubleVector_capacity(self)
    __swig_destroy__ = _LinearTerm.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _LinearTerm.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

HGRAD = _LinearTerm.HGRAD
HCURL = _LinearTerm.HCURL
HDIV = _LinearTerm.HDIV
HGRAD_DISC = _LinearTerm.HGRAD_DISC
HCURL_DISC = _LinearTerm.HCURL_DISC
HDIV_DISC = _LinearTerm.HDIV_DISC
HDIV_FREE = _LinearTerm.HDIV_FREE
L2 = _LinearTerm.L2
CONSTANT_SCALAR = _LinearTerm.CONSTANT_SCALAR
VECTOR_HGRAD = _LinearTerm.VECTOR_HGRAD
VECTOR_HGRAD_DISC = _LinearTerm.VECTOR_HGRAD_DISC
VECTOR_L2 = _LinearTerm.VECTOR_L2
UNKNOWN_FS = _LinearTerm.UNKNOWN_FS
OP_VALUE = _LinearTerm.OP_VALUE
OP_GRAD = _LinearTerm.OP_GRAD
OP_CURL = _LinearTerm.OP_CURL
OP_DIV = _LinearTerm.OP_DIV
OP_D1 = _LinearTerm.OP_D1
OP_D2 = _LinearTerm.OP_D2
OP_D3 = _LinearTerm.OP_D3
OP_D4 = _LinearTerm.OP_D4
OP_D5 = _LinearTerm.OP_D5
OP_D6 = _LinearTerm.OP_D6
OP_D7 = _LinearTerm.OP_D7
OP_D8 = _LinearTerm.OP_D8
OP_D9 = _LinearTerm.OP_D9
OP_D10 = _LinearTerm.OP_D10
OP_X = _LinearTerm.OP_X
OP_Y = _LinearTerm.OP_Y
OP_Z = _LinearTerm.OP_Z
OP_DX = _LinearTerm.OP_DX
OP_DY = _LinearTerm.OP_DY
OP_DZ = _LinearTerm.OP_DZ
OP_CROSS_NORMAL = _LinearTerm.OP_CROSS_NORMAL
OP_DOT_NORMAL = _LinearTerm.OP_DOT_NORMAL
OP_TIMES_NORMAL = _LinearTerm.OP_TIMES_NORMAL
OP_TIMES_NORMAL_X = _LinearTerm.OP_TIMES_NORMAL_X
OP_TIMES_NORMAL_Y = _LinearTerm.OP_TIMES_NORMAL_Y
OP_TIMES_NORMAL_Z = _LinearTerm.OP_TIMES_NORMAL_Z
OP_TIMES_NORMAL_T = _LinearTerm.OP_TIMES_NORMAL_T
OP_VECTORIZE_VALUE = _LinearTerm.OP_VECTORIZE_VALUE
TEST = _LinearTerm.TEST
FIELD = _LinearTerm.FIELD
TRACE = _LinearTerm.TRACE
FLUX = _LinearTerm.FLUX
UNKNOWN_TYPE = _LinearTerm.UNKNOWN_TYPE
MIXED_TYPE = _LinearTerm.MIXED_TYPE
class Var(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Var, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Var, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def ID(self): return _LinearTerm.Var_ID(self)
    def name(self): return _LinearTerm.Var_name(self)
    def displayString(self): return _LinearTerm.Var_displayString(self)
    def rank(self): return _LinearTerm.Var_rank(self)
    def space(self): return _LinearTerm.Var_space(self)
    def varType(self): return _LinearTerm.Var_varType(self)
    def op(self): return _LinearTerm.Var_op(self)
    def termTraced(self): return _LinearTerm.Var_termTraced(self)
    def grad(self): return _LinearTerm.Var_grad(self)
    def div(self): return _LinearTerm.Var_div(self)
    def curl(self, *args): return _LinearTerm.Var_curl(self, *args)
    def dx(self): return _LinearTerm.Var_dx(self)
    def dy(self): return _LinearTerm.Var_dy(self)
    def x(self): return _LinearTerm.Var_x(self)
    def y(self): return _LinearTerm.Var_y(self)
    __swig_destroy__ = _LinearTerm.delete_Var
    __del__ = lambda self : None;
Var_swigregister = _LinearTerm.Var_swigregister
Var_swigregister(Var)

class VarPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VarPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VarPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _LinearTerm.VarPtr___deref__(self)
    def __mul__(self, *args): return _LinearTerm.VarPtr___mul__(self, *args)
    def __rmul__(self, *args): return _LinearTerm.VarPtr___rmul__(self, *args)
    def __add__(self, *args): return _LinearTerm.VarPtr___add__(self, *args)
    def __div__(self, *args): return _LinearTerm.VarPtr___div__(self, *args)
    def __sub__(self, *args): return _LinearTerm.VarPtr___sub__(self, *args)
    def __neg__(self): return _LinearTerm.VarPtr___neg__(self)
    def __init__(self): 
        this = _LinearTerm.new_VarPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LinearTerm.delete_VarPtr
    __del__ = lambda self : None;
    def ID(self): return _LinearTerm.VarPtr_ID(self)
    def name(self): return _LinearTerm.VarPtr_name(self)
    def displayString(self): return _LinearTerm.VarPtr_displayString(self)
    def rank(self): return _LinearTerm.VarPtr_rank(self)
    def space(self): return _LinearTerm.VarPtr_space(self)
    def varType(self): return _LinearTerm.VarPtr_varType(self)
    def op(self): return _LinearTerm.VarPtr_op(self)
    def termTraced(self): return _LinearTerm.VarPtr_termTraced(self)
    def grad(self): return _LinearTerm.VarPtr_grad(self)
    def div(self): return _LinearTerm.VarPtr_div(self)
    def curl(self, *args): return _LinearTerm.VarPtr_curl(self, *args)
    def dx(self): return _LinearTerm.VarPtr_dx(self)
    def dy(self): return _LinearTerm.VarPtr_dy(self)
    def x(self): return _LinearTerm.VarPtr_x(self)
    def y(self): return _LinearTerm.VarPtr_y(self)
VarPtr_swigregister = _LinearTerm.VarPtr_swigregister
VarPtr_swigregister(VarPtr)

class map_int_FunctionPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, map_int_FunctionPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, map_int_FunctionPtr, name)
    __repr__ = _swig_repr
    def iterator(self): return _LinearTerm.map_int_FunctionPtr_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _LinearTerm.map_int_FunctionPtr___nonzero__(self)
    def __bool__(self): return _LinearTerm.map_int_FunctionPtr___bool__(self)
    def __len__(self): return _LinearTerm.map_int_FunctionPtr___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _LinearTerm.map_int_FunctionPtr___getitem__(self, *args)
    def __delitem__(self, *args): return _LinearTerm.map_int_FunctionPtr___delitem__(self, *args)
    def has_key(self, *args): return _LinearTerm.map_int_FunctionPtr_has_key(self, *args)
    def keys(self): return _LinearTerm.map_int_FunctionPtr_keys(self)
    def values(self): return _LinearTerm.map_int_FunctionPtr_values(self)
    def items(self): return _LinearTerm.map_int_FunctionPtr_items(self)
    def __contains__(self, *args): return _LinearTerm.map_int_FunctionPtr___contains__(self, *args)
    def key_iterator(self): return _LinearTerm.map_int_FunctionPtr_key_iterator(self)
    def value_iterator(self): return _LinearTerm.map_int_FunctionPtr_value_iterator(self)
    def __setitem__(self, *args): return _LinearTerm.map_int_FunctionPtr___setitem__(self, *args)
    def asdict(self): return _LinearTerm.map_int_FunctionPtr_asdict(self)
    def __init__(self, *args): 
        this = _LinearTerm.new_map_int_FunctionPtr(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _LinearTerm.map_int_FunctionPtr_empty(self)
    def size(self): return _LinearTerm.map_int_FunctionPtr_size(self)
    def clear(self): return _LinearTerm.map_int_FunctionPtr_clear(self)
    def swap(self, *args): return _LinearTerm.map_int_FunctionPtr_swap(self, *args)
    def get_allocator(self): return _LinearTerm.map_int_FunctionPtr_get_allocator(self)
    def begin(self): return _LinearTerm.map_int_FunctionPtr_begin(self)
    def end(self): return _LinearTerm.map_int_FunctionPtr_end(self)
    def rbegin(self): return _LinearTerm.map_int_FunctionPtr_rbegin(self)
    def rend(self): return _LinearTerm.map_int_FunctionPtr_rend(self)
    def count(self, *args): return _LinearTerm.map_int_FunctionPtr_count(self, *args)
    def erase(self, *args): return _LinearTerm.map_int_FunctionPtr_erase(self, *args)
    def find(self, *args): return _LinearTerm.map_int_FunctionPtr_find(self, *args)
    def lower_bound(self, *args): return _LinearTerm.map_int_FunctionPtr_lower_bound(self, *args)
    def upper_bound(self, *args): return _LinearTerm.map_int_FunctionPtr_upper_bound(self, *args)
    __swig_destroy__ = _LinearTerm.delete_map_int_FunctionPtr
    __del__ = lambda self : None;
map_int_FunctionPtr_swigregister = _LinearTerm.map_int_FunctionPtr_swigregister
map_int_FunctionPtr_swigregister(map_int_FunctionPtr)

class set_int(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, set_int, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, set_int, name)
    __repr__ = _swig_repr
    def iterator(self): return _LinearTerm.set_int_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _LinearTerm.set_int___nonzero__(self)
    def __bool__(self): return _LinearTerm.set_int___bool__(self)
    def __len__(self): return _LinearTerm.set_int___len__(self)
    def append(self, *args): return _LinearTerm.set_int_append(self, *args)
    def __contains__(self, *args): return _LinearTerm.set_int___contains__(self, *args)
    def __getitem__(self, *args): return _LinearTerm.set_int___getitem__(self, *args)
    def add(self, *args): return _LinearTerm.set_int_add(self, *args)
    def discard(self, *args): return _LinearTerm.set_int_discard(self, *args)
    def __init__(self, *args): 
        this = _LinearTerm.new_set_int(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _LinearTerm.set_int_empty(self)
    def size(self): return _LinearTerm.set_int_size(self)
    def clear(self): return _LinearTerm.set_int_clear(self)
    def swap(self, *args): return _LinearTerm.set_int_swap(self, *args)
    def count(self, *args): return _LinearTerm.set_int_count(self, *args)
    def begin(self): return _LinearTerm.set_int_begin(self)
    def end(self): return _LinearTerm.set_int_end(self)
    def rbegin(self): return _LinearTerm.set_int_rbegin(self)
    def rend(self): return _LinearTerm.set_int_rend(self)
    def erase(self, *args): return _LinearTerm.set_int_erase(self, *args)
    def find(self, *args): return _LinearTerm.set_int_find(self, *args)
    def lower_bound(self, *args): return _LinearTerm.set_int_lower_bound(self, *args)
    def upper_bound(self, *args): return _LinearTerm.set_int_upper_bound(self, *args)
    def equal_range(self, *args): return _LinearTerm.set_int_equal_range(self, *args)
    def insert(self, *args): return _LinearTerm.set_int_insert(self, *args)
    __swig_destroy__ = _LinearTerm.delete_set_int
    __del__ = lambda self : None;
set_int_swigregister = _LinearTerm.set_int_swigregister
set_int_swigregister(set_int)

class LinearTerm(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearTerm, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearTerm, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _LinearTerm.new_LinearTerm()
        try: self.this.append(this)
        except: self.this = this
    def varIDs(self): return _LinearTerm.LinearTerm_varIDs(self)
    def termType(self): return _LinearTerm.LinearTerm_termType(self)
    def evaluate(self, *args): return _LinearTerm.LinearTerm_evaluate(self, *args)
    def rank(self): return _LinearTerm.LinearTerm_rank(self)
    def displayString(self): return _LinearTerm.LinearTerm_displayString(self)
    __swig_destroy__ = _LinearTerm.delete_LinearTerm
    __del__ = lambda self : None;
LinearTerm_swigregister = _LinearTerm.LinearTerm_swigregister
LinearTerm_swigregister(LinearTerm)

class LinearTermPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinearTermPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinearTermPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _LinearTerm.LinearTermPtr___deref__(self)
    def __add__(self, *args): return _LinearTerm.LinearTermPtr___add__(self, *args)
    def __rmul__(self, *args): return _LinearTerm.LinearTermPtr___rmul__(self, *args)
    def __neg__(self): return _LinearTerm.LinearTermPtr___neg__(self)
    def __sub__(self, *args): return _LinearTerm.LinearTermPtr___sub__(self, *args)
    def __init__(self): 
        this = _LinearTerm.new_LinearTermPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _LinearTerm.delete_LinearTermPtr
    __del__ = lambda self : None;
    def varIDs(self): return _LinearTerm.LinearTermPtr_varIDs(self)
    def termType(self): return _LinearTerm.LinearTermPtr_termType(self)
    def evaluate(self, *args): return _LinearTerm.LinearTermPtr_evaluate(self, *args)
    def rank(self): return _LinearTerm.LinearTermPtr_rank(self)
    def displayString(self): return _LinearTerm.LinearTermPtr_displayString(self)
LinearTermPtr_swigregister = _LinearTerm.LinearTermPtr_swigregister
LinearTermPtr_swigregister(LinearTermPtr)

# This file is compatible with both classic and new-style classes.


