# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Mesh', [dirname(__file__)])
        except ImportError:
            import _Mesh
            return _Mesh
        if fp is not None:
            try:
                _mod = imp.load_module('_Mesh', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Mesh = swig_import_helper()
    del swig_import_helper
else:
    import _Mesh
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Mesh.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _Mesh.SwigPyIterator_value(self)
    def incr(self, n=1): return _Mesh.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _Mesh.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _Mesh.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _Mesh.SwigPyIterator_equal(self, *args)
    def copy(self): return _Mesh.SwigPyIterator_copy(self)
    def next(self): return _Mesh.SwigPyIterator_next(self)
    def __next__(self): return _Mesh.SwigPyIterator___next__(self)
    def previous(self): return _Mesh.SwigPyIterator_previous(self)
    def advance(self, *args): return _Mesh.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _Mesh.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _Mesh.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _Mesh.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _Mesh.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _Mesh.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _Mesh.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _Mesh.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _Mesh.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _Mesh.IntVector___nonzero__(self)
    def __bool__(self): return _Mesh.IntVector___bool__(self)
    def __len__(self): return _Mesh.IntVector___len__(self)
    def pop(self): return _Mesh.IntVector_pop(self)
    def __getslice__(self, *args): return _Mesh.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _Mesh.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _Mesh.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _Mesh.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _Mesh.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _Mesh.IntVector___setitem__(self, *args)
    def append(self, *args): return _Mesh.IntVector_append(self, *args)
    def empty(self): return _Mesh.IntVector_empty(self)
    def size(self): return _Mesh.IntVector_size(self)
    def clear(self): return _Mesh.IntVector_clear(self)
    def swap(self, *args): return _Mesh.IntVector_swap(self, *args)
    def get_allocator(self): return _Mesh.IntVector_get_allocator(self)
    def begin(self): return _Mesh.IntVector_begin(self)
    def end(self): return _Mesh.IntVector_end(self)
    def rbegin(self): return _Mesh.IntVector_rbegin(self)
    def rend(self): return _Mesh.IntVector_rend(self)
    def pop_back(self): return _Mesh.IntVector_pop_back(self)
    def erase(self, *args): return _Mesh.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _Mesh.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _Mesh.IntVector_push_back(self, *args)
    def front(self): return _Mesh.IntVector_front(self)
    def back(self): return _Mesh.IntVector_back(self)
    def assign(self, *args): return _Mesh.IntVector_assign(self, *args)
    def resize(self, *args): return _Mesh.IntVector_resize(self, *args)
    def insert(self, *args): return _Mesh.IntVector_insert(self, *args)
    def reserve(self, *args): return _Mesh.IntVector_reserve(self, *args)
    def capacity(self): return _Mesh.IntVector_capacity(self)
    __swig_destroy__ = _Mesh.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _Mesh.IntVector_swigregister
IntVector_swigregister(IntVector)

class UnsignedSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnsignedSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, UnsignedSet, name)
    __repr__ = _swig_repr
    def iterator(self): return _Mesh.UnsignedSet_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _Mesh.UnsignedSet___nonzero__(self)
    def __bool__(self): return _Mesh.UnsignedSet___bool__(self)
    def __len__(self): return _Mesh.UnsignedSet___len__(self)
    def append(self, *args): return _Mesh.UnsignedSet_append(self, *args)
    def __contains__(self, *args): return _Mesh.UnsignedSet___contains__(self, *args)
    def __getitem__(self, *args): return _Mesh.UnsignedSet___getitem__(self, *args)
    def add(self, *args): return _Mesh.UnsignedSet_add(self, *args)
    def discard(self, *args): return _Mesh.UnsignedSet_discard(self, *args)
    def __init__(self, *args): 
        this = _Mesh.new_UnsignedSet(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _Mesh.UnsignedSet_empty(self)
    def size(self): return _Mesh.UnsignedSet_size(self)
    def clear(self): return _Mesh.UnsignedSet_clear(self)
    def swap(self, *args): return _Mesh.UnsignedSet_swap(self, *args)
    def count(self, *args): return _Mesh.UnsignedSet_count(self, *args)
    def begin(self): return _Mesh.UnsignedSet_begin(self)
    def end(self): return _Mesh.UnsignedSet_end(self)
    def rbegin(self): return _Mesh.UnsignedSet_rbegin(self)
    def rend(self): return _Mesh.UnsignedSet_rend(self)
    def erase(self, *args): return _Mesh.UnsignedSet_erase(self, *args)
    def find(self, *args): return _Mesh.UnsignedSet_find(self, *args)
    def lower_bound(self, *args): return _Mesh.UnsignedSet_lower_bound(self, *args)
    def upper_bound(self, *args): return _Mesh.UnsignedSet_upper_bound(self, *args)
    def equal_range(self, *args): return _Mesh.UnsignedSet_equal_range(self, *args)
    def insert(self, *args): return _Mesh.UnsignedSet_insert(self, *args)
    __swig_destroy__ = _Mesh.delete_UnsignedSet
    __del__ = lambda self : None;
UnsignedSet_swigregister = _Mesh.UnsignedSet_swigregister
UnsignedSet_swigregister(UnsignedSet)

class Mesh(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Mesh, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Mesh, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def saveToHDF5(self, *args): return _Mesh.Mesh_saveToHDF5(self, *args)
    def cellPolyOrder(self, *args): return _Mesh.Mesh_cellPolyOrder(self, *args)
    def getActiveCellIDs(self): return _Mesh.Mesh_getActiveCellIDs(self)
    def hRefine(self, *args): return _Mesh.Mesh_hRefine(self, *args)
    def numActiveElements(self): return _Mesh.Mesh_numActiveElements(self)
    def numFluxDofs(self): return _Mesh.Mesh_numFluxDofs(self)
    def numFieldDofs(self): return _Mesh.Mesh_numFieldDofs(self)
    def numGlobalDofs(self): return _Mesh.Mesh_numGlobalDofs(self)
    def numElements(self): return _Mesh.Mesh_numElements(self)
    def pRefine(self, *args): return _Mesh.Mesh_pRefine(self, *args)
    def registerSolution(self, *args): return _Mesh.Mesh_registerSolution(self, *args)
    def vertexIndicesForCell(self, *args): return _Mesh.Mesh_vertexIndicesForCell(self, *args)
    def verticesForCell(self, *args): return _Mesh.Mesh_verticesForCell(self, *args)
    __swig_destroy__ = _Mesh.delete_Mesh
    __del__ = lambda self : None;
Mesh_swigregister = _Mesh.Mesh_swigregister
Mesh_swigregister(Mesh)

class MeshPtr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MeshPtr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MeshPtr, name)
    __repr__ = _swig_repr
    def __deref__(self): return _Mesh.MeshPtr___deref__(self)
    def __init__(self): 
        this = _Mesh.new_MeshPtr()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Mesh.delete_MeshPtr
    __del__ = lambda self : None;
    def saveToHDF5(self, *args): return _Mesh.MeshPtr_saveToHDF5(self, *args)
    def cellPolyOrder(self, *args): return _Mesh.MeshPtr_cellPolyOrder(self, *args)
    def getActiveCellIDs(self): return _Mesh.MeshPtr_getActiveCellIDs(self)
    def hRefine(self, *args): return _Mesh.MeshPtr_hRefine(self, *args)
    def numActiveElements(self): return _Mesh.MeshPtr_numActiveElements(self)
    def numFluxDofs(self): return _Mesh.MeshPtr_numFluxDofs(self)
    def numFieldDofs(self): return _Mesh.MeshPtr_numFieldDofs(self)
    def numGlobalDofs(self): return _Mesh.MeshPtr_numGlobalDofs(self)
    def numElements(self): return _Mesh.MeshPtr_numElements(self)
    def pRefine(self, *args): return _Mesh.MeshPtr_pRefine(self, *args)
    def registerSolution(self, *args): return _Mesh.MeshPtr_registerSolution(self, *args)
    def vertexIndicesForCell(self, *args): return _Mesh.MeshPtr_vertexIndicesForCell(self, *args)
    def verticesForCell(self, *args): return _Mesh.MeshPtr_verticesForCell(self, *args)
MeshPtr_swigregister = _Mesh.MeshPtr_swigregister
MeshPtr_swigregister(MeshPtr)

# This file is compatible with both classic and new-style classes.


